language: node_js
matrix:
  include:
    - node_js: 10
      env: HUGO_ENV=dev
    - node_js: 12
      env: HUGO_ENV=production
install:
- npm install
- wget https://github.com/gohugoio/hugo/releases/download/v0.76.5/hugo_0.76.5_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
script:
 - if [ "$HUGO_ENV" = "dev" ]; then hugo --gc --minify --buildFuture; fi;
 - if [ "$HUGO_ENV" = "production" ]; then hugo --gc --minify ; fi;